### ISSUE TITLE
Readme is not synchronised with `aws-lc-verification`

### ISSUE THREAD

**Issue by stormshield-gt** [aws/aws-lc#1404]
This repository readme  [states that AES-GCM is formally verified](https://github.com/aws/aws-lc#formal-verification) but in the `aws-lc-verification` one, it's [states that only AES-KWP is formally verified](https://github.com/awslabs/aws-lc-verification#verified-code).

I don't know which one is right.

**Comment by pennyannn** [comment]
Hi @stormshield-gt, thanks for reaching out. The README of `AWS-LC-Verification` contains the most recent information. The description in AWS-LC is indeed not recent enough. I will submit a PR to address this issue.
