### ISSUE TITLE
Compiling with zig for x86_64-windows-gnu fails due to X509_NAME and wincrypt.h

### ISSUE THREAD

**Issue by theoparis** [aws/aws-lc#1434]
### Problem:

When I tried to compile aws-lc using a build.zig file instead of cmake, for a x86_64-windows-gnu target, It fails due to conflicting symbols from wincrypt.h. Curl seems to have worked around it by using #undef but I'd have to keep a maintained fork of aws-lc to make those changes myself here...

See https://github.com/curl/curl/commit/4c46c829f5ed7c37b3313c67a6662b7332c1ff7f

#### Reproduction

Git clone [the aws-lc zig build repository](https://github.com/zigachads/boringssl) and extract [the latest zig master tarball](https://ziglang.org/download). Run `zig build -Dtarget=x86_64-windows-gnu` - it should fail with a bunch of X509_NAME errors...

#### Relevant details

AWS-LC commit: `56def5a253d27280f3b7bd6564cfa5a11211aee8`

System information: for linux, below info can be collected by running `uname -srvmp`
 * CPU architecture: (x86-64)
 * CPU name: (Intel i5-2430M)  
 * OS: (Arch Linux)  

Build log: 

```
/home/theo/.cache/zig/p/1220b404f239d0911665e3328c7574d8bf6b0f6bd2b0af9761cb2af7ea0eada6c6df/ssl/ssl_file.cc:146:26: error: expected ')'
    int (*old_cmp)(const X509_NAME *const *, const X509_NAME *const *);
                         ^
/home/theo/dev/zig.git/expidus/build/stage3/lib/zig/libc/include/any-windows-any/wincrypt.h:1515:29: note: expanded from macro 'X509_NAME'
#define X509_NAME ((LPCSTR) 7)
```

**Comment by torben-hansen** [comment]
Thanks for the report. Researching, this seems as a general issue with `wincrypt.h`.
* What's the fix you have applied locally?
* Have you confirmed that fix resolves your issue?

Feel free to submit a PR with a fix you believe resolves your issue.

**Comment by torben-hansen** [comment]
This also look interesting: https://github.com/openssl/openssl/pull/18131#discussion_r854415820. Wonder what the status of that work is.

**Comment by theoparis** [comment]
This is still an issue but I'm not sure what the best way to fix this in aws-lc is.
