### ISSUE TITLE
Plans to replace code under the OpenSSL license?

### ISSUE THREAD

**Issue by joshtriplett** [aws/aws-lc#1441]
OpenSSL 3.0 has relicensed under Apache-2.0. aws-lc is a fork of BoringSSL which is a fork of pre-3.0 OpenSSL, so it inherits the old incompatible OpenSSL license. Do you have any plans to replace the code inherited from BoringSSL with code from OpenSSL 3.0, so that users of aws-lc can have the compatibility of Apache-2.0 without dealing with OpenSSL license incompatibilities?

**Comment by justsmth** [comment]
We don't currently have such a migration planned. I'll check whether licensing clarifications might be appropriate.

**Comment by justsmth** [comment]
Hi @joshtriplett -- I verified that we have no plans for changes that would affect our current licensing.
