### ISSUE TITLE
Memory usage per tls session

### ISSUE THREAD

**Issue by rock59** [aws/aws-lc#1806]
OpenSSL consumes 13KB memory per tls session with SSL_MODE_RELEASE_BUFFERS. s2n-tls consumes 4KB and WolfSSL uses between 1–36 KB per tls session.
 
Please clarify how much memory is consumed by aws-lc per tls session.

Thank you

**Comment by torben-hansen** [comment]
Hi Rock59, thanks for the question. I'm afraid we haven't run such memory benchmarks recently. The amount of memory consumed by AWS-LC depends on various factors such as the algorithms used, configurations of AWS-LC in your application, etc. We would encourage you to perform your own benchmarks in your application. If you observe any issues with memory usage, please let us know!

**Comment by rock59** [comment]
@torben-hansen Thank you for your response.
