### ISSUE TITLE
question: is there a way to find out the installed aws-lc version?

### ISSUE THREAD

**Issue by lucykorea414** [aws/aws-lc#1814]
I want to check if I installed the aws-lc with fips mode or not.
Is there a code/function for checking the version?

**Comment by torben-hansen** [comment]
Hi,

If you want to assert whether the AWS-LC libcrypto library loaded at run-time is build with `-DFIPS=1`, you can use the function `FIPS_mode()`: https://github.com/aws/aws-lc/blob/main/include/openssl/crypto.h#L121. It returns `1` if your AWS-LC version was build with `-DFIPS=1`.

Additionally, `OpenSSL_version()` returns information about the version number: https://github.com/aws/aws-lc/blob/main/include/openssl/crypto.h#L156.

**Comment by lucykorea414** [comment]
thanks!
