### ISSUE TITLE
Future test error in OCSPTest.TestGoodOCSP

### ISSUE THREAD

**Issue by greghogan** [aws/aws-lc#1889]
### Problem:

When setting the system time into the future (+10 years in my case) the `OCSPTest.TestGoodOCSP` test breaks with the errors read out-of-order.

#### Relevant details
AWS-LC version: 1.36.0 and 1.34.2

System information:
 * CPU architecture: x86-64
 * CPU name: AMD EPYC 9R14
 * OS: Amazon Linux 2

Test log v1.36.0:
```
[----------] 15 tests from OCSPTest
[ RUN      ] OCSPTest.TestGoodOCSP
/tmp/guix-build-aws-lc-1.36.0.drv-0/source/crypto/ocsp/ocsp_test.cc:421: Failure
Expected equality of these values:
  126
  ERR_GET_REASON(err)
    Which is: 125
/tmp/guix-build-aws-lc-1.36.0.drv-0/source/crypto/ocsp/ocsp_test.cc:423: Failure
Expected equality of these values:
  125
  ERR_GET_REASON(err)
    Which is: 126
```

Test log v1.34.2:
```text
[----------] 15 tests from OCSPTest
[ RUN      ] OCSPTest.TestGoodOCSP
/tmp/guix-build-aws-lc-1.34.2.drv-0/source/crypto/ocsp/ocsp_test.cc:441: Failure
Expected equality of these values:
  126
  ERR_GET_REASON(err)
    Which is: 125
/tmp/guix-build-aws-lc-1.34.2.drv-0/source/crypto/ocsp/ocsp_test.cc:443: Failure
Expected equality of these values:
  125
  ERR_GET_REASON(err)
    Which is: 126
[  FAILED  ] OCSPTest.TestGoodOCSP (0 ms)
```

**Comment by samuel40791765** [comment]
Thanks for reporting this! We were trying to avoid testing time-bombs when developing this, but didn't realize that the offset could trigger the inverse happening when the checked time-field is outdated. I'll put up a change to fix this.
